---
argument_specs:
  main:
    options:
      yum_cache_directory:
        type: path
      yum_cache_valid_time:
        type: int
      yum_cache_use_backend:
        type: str
        choices:
          - auto
          - dnf4
          - dnf5
