---
- name: Ensure yum repositories
  tags:
    - yum
    - yum_repositories
  block:
    - name: Ensure yum repositories
      ansible.builtin.import_tasks: repositories.yml
    - name: Ensure yum cache is up to date
      ansible.builtin.meta: flush_handlers
