---
yum_packages: [] # noqa: var-naming[no-role-prefix]
yum_packages_absent: []
yum_packages_unversioned: []
yum_packages_versioned: []
yum_packages_latest: []
yum_packages_state: present
yum_packages_allow_downgrade: false
yum_packages_lock_timeout: 60
yum_packages_use_backend: auto
