---
argument_specs:
  main:
    options:
      yum_packages:
        type: list
        elements: dict
        options:
          name:
            required: true
            type: str
          version:
            type: str
          allow_downgrade:
            type: bool
          lock_timeout:
            type: int
          state:
            type: str
            choices:
              - absent
              - present
          use_backend:
            type: str
      yum_packages_use_backend:
        type: str
