---
argument_specs:
  main:
    options:
      yum_packages:
        type: list
        elements: dict
        options:
          name:
            required: true
            type: str
          version:
            type: str
          state:
            type: str
            choices:
              - absent
              - present
      yum_packages_state:
        type: str
        choices:
          - absent
          - present
      yum_packages_allow_downgrade:
        type: bool
      yum_packages_lock_timeout:
        type: int
      yum_packages_use_backend:
        type: str
        choices:
          - auto
          - dnf4
          - dnf5
